---
# https://linuxconfig.org/how-to-move-docker-s-default-var-lib-docker-to-another-directory-on-ubuntu-debian-linux
- name: format docker disk
  become: true
  filesystem:
    fstype: ext4
    dev: "/dev/{{dev_disk_name}}"
- name: mount first disk
  become: true 
  mount:
    path: "{{docker_direc}}"
    src: /dev/{{dev_disk_name}}
    fstype: ext4
    state: mounted
- name: stop docker daemon
  systemd:
    name: "docker"
    state: stopped
    enabled: yes
  become: true
- name: drop in docker file with new docker path
  template:
    src: docker.service.j2
    dest: /lib/systemd/system/docker.service
  become: true
- name: wait for docker daemon to be completely gone 
  shell: ps aux | grep -i docker | grep -v grep
  register: docker_check
  retries: 10
  until: docker_check.rc == 1
  failed_when: docker_check.rc == 7
  become: true
- name: reload systemd and restart the docker service
  systemd:
    name: "docker"
    daemon_reload: yes
    state: restarted
    enabled: yes
  become: true